apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  completions: 10
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - name: hello-job
        image: busybox
        command:
          - echo
          - Hello im from job
        imagePullPolicy: Always
      restartPolicy: OnFailure
