##########  kubectl run nginx-critical --image=nginx --dry-run=client  -o yaml  ############
########## using the POD Manifest file  ##########################
########## Copy the content and create a file nginx-critical.yaml under /etc/kubernetes/manifests  ############


apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  run: nginx-critical
  name: nginx-critical
spec:
  containers:
  - image: nginx
    name: nginx-critical
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
