apiVersion: v1
kind: Pod  
metadata: 
 name: multi-pod 
spec:
 containers: 
 - name: alpha 
   image: nginx
   ports: 
   - containerPort: 80
 - name: beta
   image: busybox
   command: ["/bin/sh"]
   args: ["-c", "while true; do echo hello; sleep 4800;done"]
   ports: 
   - containerPort: 8080
