apiVersion: v1
kind: Pod  
metadata: 
 name: multi-pod 
spec:
 containers: 
 - name: alpha 
   image: nginx
   ports: 
   - containerPort: 80
 - name: beta
   image: busybox
   ports: 
   - containerPort: 8080
