apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    environment: prod
spec:
  containers:
  - name: nginx-multipods
    image: nginx
    
---

apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    environment: prod
spec:
  containers:
  - name: nginx-multipods
    image: nginx

---

apiVersion: v1
kind: Pod
metadata:
  name: pod3
  labels:
    environment: dev
spec:
  containers:
  - name: nginx-multipods
    image: nginx

---

apiVersion: v1
kind: Pod
metadata:
  name: pod4
  labels:
    environment: dev
spec:
  containers:
  - name: nginx-multipods
    image: nginx

---

apiVersion: v1
kind: Pod
metadata:
  name: pod5
  labels:
    environment: dev
spec:
  containers:
  - name: nginx-multipods
    image: nginx
