kind: Pod
apiVersion: v1
metadata:
  name: pod-env-var
spec:
  containers:
    - name: env-var-configmap
      image: nginx
      envFrom:
        - configMapRef:
            name: keyvalcfgmap
            
            
            
########################## Verify ###########################
kubectl exec pod-env-var -- printenv
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=pod-env-var
NGINX_VERSION=1.23.3
NJS_VERSION=0.7.9
PKG_RELEASE=1~bullseye
config.txt=key1=value1
key2=value2

